name: Update NFL Scoreboard

on:
  schedule:
    # Every 5 minutes during game windows (Sat-Mon, 10am-11pm PT)
    - cron: '*/5 17-7 * 9-2 0,1,6'  # Approximate NFL season window
  workflow_dispatch:  # Manual trigger

permissions:
  contents: write
  pages: write

jobs:
  update-scores:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: pip install requests
      
      - name: Fetch NFL data
        env:
          SPORTSBLAZE_API_KEY: ${{ secrets.SPORTSBLAZE_API_KEY }}
        run: python fetch_nfl.py
      - name: Debug file location
        run: |
          echo "Current directory:"
          pwd
          echo "Looking for JSON files:"
          find . -name "*.json" -type f
          echo "Contents of docs/:"
          ls -la docs/ || echo "docs/ not found"
          echo "Git status:"
          git status
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/nfl_games.json
          git diff --staged --quiet || git commit -m "Update NFL scores $(date -u +%Y-%m-%dT%H:%M:%SZ)"
          git push
